package util;

/**
 * Created by MarioJ on 07/04/15.
 */
public class Tag {

    public enum HTTP {
        CHECK_ACCOUNT, NAME_UPDATE, STATUS_UPDATE, PHOTO_UPDATE, ACCOUNT_RETRIEVE, NAME_RETRIEVE, STATUS_RETRIEVE, LAST_MODIFIED_TN_RETRIEVE, PHOTO_TN_RETRIEVE,
        PHOTO_RETRIEVE, SYNCRONIZE_CONTACTS, CHECK_UPDATES
    }

}
